import React, { useEffect, useMemo, useState } from "react";
import {
  ArrowLeft, ArrowRight, Bell, Bot, CalendarClock, Check, CheckCircle2, ChevronRight,
  CircleHelp, ClipboardCheck, FileCheck2, FileText, FolderOpen, Globe2, Home, Languages,
  LayoutDashboard, Menu, Mic, Pencil, Plus, Search, Settings, ShieldCheck, Sparkles,
  Upload, Volume2, X, AlertTriangle, Clock3, ExternalLink, MessageCircle, SlidersHorizontal
} from "lucide-react";
import { checkForm, explainField, understandRequest } from "./aiService";

const LANGUAGES = ["English", "తెలుగు", "हिंदी", "मराठी", "தமிழ்", "ಕನ್ನಡ"];
const CATEGORIES = [
  ["Identity & Documents", "Aadhaar, PAN, voter ID and certificates", "🪪"],
  ["Transport", "Driving licence and vehicle services", "🚗"],
  ["Education", "Scholarships and student services", "🎓"],
  ["Welfare & Schemes", "Benefits, subsidies and assistance", "🤝"],
  ["Family & Certificates", "Birth, death, marriage, income and caste", "📄"],
  ["Property & Land", "Land records and registration", "🏠"],
  ["Business & Employment", "Business and employment services", "💼"],
  ["Health Services", "Government health services", "🏥"],
  ["Voting & Civic", "Voter and civic services", "🗳️"],
  ["Tax & Finance", "Tax and financial services", "💳"],
  ["Pension", "Pension and senior citizen services", "👴"],
  ["Passport & Travel", "Passport and travel services", "✈️"]
];
const SERVICES = [
  {id:"income", name:"Income Certificate", category:"Family & Certificates", desc:"Proof of family income for education, schemes and other applications.", docs:5},
  {id:"scholarship", name:"Scholarship Assistance", category:"Education", desc:"Understand scholarship requirements and prepare your application.", docs:5},
  {id:"driving", name:"Driving Licence", category:"Transport", desc:"Understand learner and driving licence application steps.", docs:4},
  {id:"birth", name:"Birth Certificate", category:"Family & Certificates", desc:"Learn what is needed to request a birth certificate.", docs:3},
  {id:"passport", name:"Passport", category:"Passport & Travel", desc:"Prepare information and documents for passport services.", docs:6},
  {id:"voter", name:"Voter Services", category:"Voting & Civic", desc:"Understand voter registration and correction services.", docs:4}
];
const DEFAULT_DOCS = [
  {key:"identity", name:"Identity proof", status:"available", text:"Helps identify the applicant."},
  {key:"address", name:"Address proof", status:"available", text:"Supports the address entered in the application."},
  {key:"incomeProof", name:"Income certificate", status:"missing", text:"May be required when income is part of eligibility."},
  {key:"photo", name:"Passport-size photograph", status:"not_selected", text:"A recent photograph where required."}
];
const DEMO_FORM = {name:"Ravi Kumar", dob:"2008-08-15", mobile:"987654", occupation:"", income:"25000", incomeFrequency:"", purpose:"Education"};

function App(){
  const [screen,setScreen]=useState("home");
  const [request,setRequest]=useState("");
  const [understanding,setUnderstanding]=useState(null);
  const [form,setForm]=useState(()=>load("formease_form",DEMO_FORM));
  const [docs,setDocs]=useState(()=>load("formease_docs",DEFAULT_DOCS));
  const [applications,setApplications]=useState(()=>load("formease_apps",[]));
  const [reminders,setReminders]=useState(()=>load("formease_reminders",[]));
  const [language,setLanguage]=useState(()=>load("formease_language","English"));
  const [simpleMode,setSimpleMode]=useState(false);
  const [mobileMenu,setMobileMenu]=useState(false);
  const [loading,setLoading]=useState(false);
  const [checked,setChecked]=useState(false);
  const [issues,setIssues]=useState([]);
  const [explain,setExplain]=useState(null);
  const [toast,setToast]=useState("");
  const [voice,setVoice]=useState(false);
  const [search,setSearch]=useState("");
  const [selectedService,setSelectedService]=useState(null);
  const [schemeQuery,setSchemeQuery]=useState("");
  const [activeTab,setActiveTab]=useState("all");

  useEffect(()=>localStorage.setItem("formease_form",JSON.stringify(form)),[form]);
  useEffect(()=>localStorage.setItem("formease_docs",JSON.stringify(docs)),[docs]);
  useEffect(()=>localStorage.setItem("formease_apps",JSON.stringify(applications)),[applications]);
  useEffect(()=>localStorage.setItem("formease_reminders",JSON.stringify(reminders)),[reminders]);
  useEffect(()=>localStorage.setItem("formease_language",JSON.stringify(language)),[language]);
  useEffect(()=>{ if(toast){const t=setTimeout(()=>setToast(""),2800);return()=>clearTimeout(t)}},[toast]);

  const go=(s)=>{setScreen(s);setMobileMenu(false);window.scrollTo({top:0,behavior:"smooth"})};
  const update=(k,v)=>{setForm(p=>({...p,[k]:v}));setChecked(false)};
  const age=useMemo(()=>calculateAge(form.dob),[form.dob]);
  const progress=screen==="home"?0:({need:12,service:24,documents:38,form:55,check:70,review:86,submitted:100}[screen]||0);
  const filteredServices=SERVICES.filter(s=>(s.name+s.category+s.desc).toLowerCase().includes(search.toLowerCase()));

  async function startAI(){
    if(!request.trim())return;
    setLoading(true); const result=await understandRequest(request); setUnderstanding(result); setSelectedService(result.service); setLoading(false); go("service");
  }
  function beginService(service){setSelectedService(service.name);setUnderstanding({service:service.name,purpose:service.category,explanation:service.desc});go("documents")}
  function loadDemo(){setForm({...DEMO_FORM});setDocs(DEFAULT_DOCS.map(x=>({...x})));setChecked(false);setIssues([]);setRequest("I need an income certificate for college.");setUnderstanding(null);go("need")}
  async function runCheck(){setLoading(true);const r=await checkForm({...form,age:String(age),documents:Object.fromEntries(docs.map(d=>[d.key,d.status==="available"]))});setIssues(r.issues);setChecked(true);setLoading(false)}
  function createApplication(){
    const id="FE-2026-"+Math.floor(10000+Math.random()*89999);
    const item={id,service:selectedService||"Government Service",status:"Documents Required",progress:55,date:new Date().toLocaleDateString("en-IN"),portal:"Official government portal"};
    setApplications(p=>[item,...p]);go("submitted");setToast("Application saved to My Applications");
  }
  function addReminder(){const r={id:Date.now(),title:"Check application status",date:new Date(Date.now()+86400000*3).toISOString().slice(0,10),done:false};setReminders(p=>[r,...p]);setToast("Reminder added")}
  function toggleVoice(){
    const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
    if(!SR){setToast("Voice input is not supported in this browser. Try Chrome or Edge.");return}
    const rec=new SR(); rec.lang=language==="తెలుగు"?"te-IN":language==="हिंदी"?"hi-IN":language==="मराठी"?"mr-IN":"en-IN";rec.interimResults=false;
    rec.onstart=()=>setVoice(true);rec.onend=()=>setVoice(false);rec.onerror=()=>{setVoice(false);setToast("Could not hear that. Please try again.")};rec.onresult=e=>setRequest(e.results[0][0].transcript);rec.start();
  }
  function speak(text){if("speechSynthesis" in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text))}}

  return <div className="app">
    <div className="demo-banner"><ShieldCheck size={15}/> DEMO / PROTOTYPE · Synthetic data only · No government system is connected</div>
    <header className="topbar">
      <button className="brand" onClick={()=>go("home")}><span className="brand-mark"><Sparkles size={18}/></span><span>FormEase <b>AI</b></span></button>
      <nav className={mobileMenu?"nav open":"nav"}>
        <button onClick={()=>go("home")}>Home</button><button onClick={()=>go("services")}>Services</button><button onClick={()=>go("dashboard")}>My Applications</button><button onClick={()=>go("documents")}>Documents</button><button onClick={()=>go("reminders")}>Reminders</button>
        <button className="lang" onClick={()=>setLanguage(LANGUAGES[(LANGUAGES.indexOf(language)+1)%LANGUAGES.length])}><Languages size={16}/>{language}</button>
      </nav>
      <div className="top-actions"><button className="icon-btn desktop-only" title="Simple mode" onClick={()=>setSimpleMode(!simpleMode)}><SlidersHorizontal size={17}/></button><button className="icon-btn desktop-only" onClick={()=>go("notifications")}><Bell size={17}/>{reminders.filter(r=>!r.done).length>0&&<i className="notify-dot"/>}</button><button className="profile-btn desktop-only" onClick={()=>go("profile")}>RK</button><button className="menu-btn" onClick={()=>setMobileMenu(!mobileMenu)}><Menu/></button></div>
    </header>
    {progress>0&&screen!=="submitted"&&<div className="progress-wrap"><div className="progress-top"><span>Application journey</span><b>{progress}%</b></div><div className="progress"><div style={{width:`${progress}%`}}/></div><div className="step-labels">{["Need","Service","Documents","Form","AI Check","Review"].map((x,i)=><span key={x} className={progress>=i*16+12?"active":""}>{i+1}. {x}</span>)}</div></div>}

    <main>
      {screen==="home"&&<HomePage request={request} setRequest={setRequest} startAI={startAI} loading={loading} toggleVoice={toggleVoice} voice={voice} onDemo={loadDemo} go={go} language={language}/>} 
      {screen==="need"&&<NeedPage request={request} setRequest={setRequest} startAI={startAI} loading={loading} toggleVoice={toggleVoice} voice={voice} go={go} language={language}/>} 
      {screen==="services"&&<ServicesPage search={search} setSearch={setSearch} services={filteredServices} beginService={beginService} go={go}/>} 
      {screen==="service"&&<ServicePage understanding={understanding} selectedService={selectedService} go={go} setExplain={setExplain}/>} 
      {screen==="documents"&&<DocumentsPage docs={docs} setDocs={setDocs} go={go} setExplain={setExplain} addReminder={addReminder}/>} 
      {screen==="form"&&<FormPage form={form} update={update} age={age} go={go} setExplain={setExplain} toggleVoice={toggleVoice} voice={voice}/>} 
      {screen==="check"&&<CheckPage checked={checked} issues={issues} runCheck={runCheck} loading={loading} go={go}/>} 
      {screen==="review"&&<ReviewPage form={form} docs={docs} age={age} go={go} createApplication={createApplication}/>} 
      {screen==="submitted"&&<SubmittedPage applications={applications} go={go} addReminder={addReminder}/>} 
      {screen==="dashboard"&&<Dashboard apps={applications} reminders={reminders} go={go} addReminder={addReminder}/>} 
      {screen==="reminders"&&<Reminders reminders={reminders} setReminders={setReminders} go={go}/>} 
      {screen==="notifications"&&<Notifications reminders={reminders} go={go}/>} 
      {screen==="profile"&&<Profile language={language} setLanguage={setLanguage} simpleMode={simpleMode} setSimpleMode={setSimpleMode} go={go}/>} 
      {screen==="schemes"&&<Schemes query={schemeQuery} setQuery={setSchemeQuery} go={go}/>} 
    </main>

    {explain&&<div className="modal-backdrop" onClick={()=>setExplain(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setExplain(null)}><X/></button><div className="modal-ai"><Bot/></div><span className="eyebrow">AI EXPLANATION</span><h2>{explain.title}</h2><p>{explain.text}</p><button className="btn secondary" onClick={()=>speak(explain.text)}><Volume2/> Read aloud</button></div></div>}
    {toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}
    <button className="floating-ai" onClick={()=>go("need")} title="Ask FormEase AI"><Bot size={20}/><span>Ask AI</span></button>
    <footer><div><span className="brand"><span className="brand-mark"><Sparkles size={14}/></span> FormEase <b>AI</b></span><p>An independent civic-tech prototype that helps people understand government services.</p></div><div><b>Important</b><p>FormEase AI is not a government authority. Verify requirements and submit through official sources.</p></div><div className="footer-links"><button onClick={()=>go("services")}>Services</button><button onClick={()=>go("schemes")}>Scheme Finder</button><button onClick={()=>go("profile")}>Privacy & Settings</button></div></footer>
  </div>
}

function HomePage({request,setRequest,startAI,loading,toggleVoice,voice,onDemo,go,language}){return <div className="home">
  <section className="hero"><div className="hero-copy"><div className="pill"><Sparkles size={14}/> AI-powered government service companion</div><h1>Government services,<br/><span>made simple.</span></h1><p className="hero-lead">Find the right service, understand eligibility, prepare documents, complete forms with confidence, and keep track of what happens next.</p>
  <div className="hero-ai"><div className="hero-ai-head"><Bot size={18}/><b>What do you need help with?</b><span>Text or voice</span></div><div className="hero-input"><textarea value={request} onChange={e=>setRequest(e.target.value)} placeholder="e.g. I need a scholarship for college..."/><button className={voice?"mic listening":"mic"} onClick={toggleVoice}><Mic size={20}/></button><button className="send" disabled={!request.trim()||loading} onClick={startAI}>{loading?<span className="spinner"/>:<ArrowRight/>}</button></div><div className="quick-prompts"><button onClick={()=>setRequest("I need a driving licence")}>Driving licence</button><button onClick={()=>setRequest("I need a birth certificate")}>Birth certificate</button><button onClick={()=>setRequest("Find a scholarship")}>Scholarship</button><button onClick={()=>setRequest("I need an income certificate")}>Income certificate</button></div></div>
  <div className="hero-actions"><button className="btn primary large" onClick={()=>go("services")}>Explore services <ArrowRight/></button><button className="btn secondary large" onClick={onDemo}><ZapIcon/> Try interactive demo</button></div><div className="trust-row"><ShieldCheck size={17}/><span>Plain language</span><span>•</span><span>Multilingual</span><span>•</span><span>Voice-friendly</span></div></div>
  <div className="hero-visual"><div className="dashboard-mock"><div className="mock-nav"><span>FormEase AI</span><span className="live-dot">● Live demo</span></div><div className="mock-welcome">Good morning 👋<small>Here's what needs your attention.</small></div><div className="mock-stat"><div><small>Application readiness</small><b>80%</b></div><div className="mini-ring">80</div></div><div className="mock-card"><div className="mock-icon">📄</div><div><b>Scholarship application</b><small>Documents required</small></div><span className="warning-tag">2 actions</span></div><div className="mock-card"><div className="mock-icon">🔔</div><div><b>Income certificate</b><small>Reminder in 3 days</small></div><span className="success-tag">On track</span></div><div className="mock-ai"><Bot size={18}/><span><b>Ask FormEase AI</b><small>“What do I need next?”</small></span><ChevronRight/></div></div></div></section>
  <section className="stats"><div><b>01</b><span>Tell us naturally</span></div><div><b>02</b><span>AI guides each step</span></div><div><b>03</b><span>Check before submission</span></div><div><b>04</b><span>Track & remember</span></div></section>
  <section className="section"><div className="section-heading"><span className="eyebrow">POPULAR SERVICES</span><h2>Start with what you need</h2><p>You don't need to know the exact government form name.</p></div><div className="service-grid">{SERVICES.slice(0,6).map(s=><ServiceCard key={s.id} service={s} onClick={()=>go("services")}/>)}</div><button className="btn secondary centered" onClick={()=>go("services")}>View all services <ArrowRight/></button></section>
  <section className="journey"><div><span className="eyebrow">ONE CLEAR JOURNEY</span><h2>From “I don't know where to start” to “I know what happens next.”</h2><p>FormEase is built around the citizen journey, not complicated portal menus.</p></div><div className="journey-steps">{["Tell us what you need","Find the right service","Check eligibility","Prepare documents","Fill with guidance","AI check & review","Submit officially","Track & get reminders"].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b></div>)}</div></section>
  <section className="feature-band"><div><span className="eyebrow">DESIGNED FOR ACCESS</span><h2>Use FormEase your way.</h2><p>Type, speak, switch languages, or upload a form and let the assistant explain it in simple terms.</p></div><div className="access-cards"><div><Mic/><b>Voice input</b><span>Speak instead of typing.</span></div><div><Languages/><b>{language}</b><span>Change language anytime.</span></div><div><FileCheck2/><b>Document check</b><span>Know what's missing.</span></div></div></section>
</div>}
const ZapIcon=()=> <Sparkles size={17}/>;
function NeedPage(p){return <PageShell eyebrow="STEP 1 · TELL US" title="What do you need help with?" subtitle="Describe your goal in everyday language. You don't need to know the official form name." onBack={()=>p.go("home")}><div className="ai-input-card large-card"><div className="ai-orb"><Bot/></div><div className="grow"><label>Tell FormEase what you need</label><textarea value={p.request} onChange={e=>p.setRequest(e.target.value)} placeholder="Example: I need an income certificate for my college scholarship."/><div className="input-actions"><span><Sparkles size={14}/> AI understands natural language</span><div><button className={p.voice?"icon-btn active":"icon-btn"} onClick={p.toggleVoice}><Mic size={18}/></button><button className="icon-btn" onClick={()=>speakText(p.request||"Tell us what you need.")}><Volume2 size={18}/></button></div></div></div></div><div className="suggestions"><span>Try an example:</span>{["I need a driving licence","I need a birth certificate","Find a scholarship","I need an income certificate"].map(x=><button key={x} onClick={()=>p.setRequest(x)}>{x}</button>)}</div><div className="actions"><button className="btn ghost" onClick={()=>p.go("home")}><ArrowLeft/> Back</button><button className="btn primary" disabled={!p.request.trim()||p.loading} onClick={p.startAI}>{p.loading?"Understanding...":"Understand my need"}<ArrowRight/></button></div></PageShell>}
function ServicesPage({search,setSearch,services,beginService,go}){return <PageShell eyebrow="SERVICE DISCOVERY" title="Find a government service" subtitle="Search by service name or browse by what you want to accomplish." onBack={()=>go("home")}><div className="search-box"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search services, certificates, licences..."/><span>⌘ K</span></div><div className="category-grid">{CATEGORIES.map(([n,d,i])=><button key={n} className="category-card" onClick={()=>setSearch(n)}><span className="category-emoji">{i}</span><span><b>{n}</b><small>{d}</small></span><ChevronRight/></button>)}</div><div className="section-mini"><div className="section-row"><div><span className="eyebrow">SERVICES</span><h2>{services.length} services available</h2></div><button className="btn text-only" onClick={()=>go("schemes")}><Sparkles size={16}/> Find schemes</button></div><div className="service-grid">{services.map(s=><ServiceCard key={s.id} service={s} onClick={()=>beginService(s)}/>)}</div></div></PageShell>}
function ServiceCard({service,onClick}){return <button className="service-card" onClick={onClick}><div className="service-icon"><FileText size={20}/></div><div className="service-body"><span className="eyebrow">{service.category}</span><h3>{service.name}</h3><p>{service.desc}</p><div className="service-meta"><span><FileCheck2 size={13}/> {service.docs} docs</span><span>Guided</span></div></div><ChevronRight className="service-arrow"/></button>}
function ServicePage({understanding,selectedService,go,setExplain}){return <PageShell eyebrow="STEP 2 · SERVICE" title="Here's what FormEase understood" subtitle="We'll keep the process simple and show you what happens next." onBack={()=>go("need")}><div className="understand-card"><div className="check-circle"><Check/></div><div><span className="muted">You may be looking for</span><h2>{selectedService||understanding?.service||"Government service"}</h2><p>{understanding?.explanation||"We'll guide you through the relevant information, documents and next steps."}</p></div></div><div className="two-col"><InfoCard icon={<ClipboardCheck/>} title="Purpose" text={understanding?.purpose||"Government service"}/><InfoCard icon={<FileCheck2/>} title="Next" text="Check documents and prepare your application."/></div><div className="notice"><ShieldCheck size={18}/><div><b>Guidance, not approval</b><p>Requirements can vary by service, state and time. Verify final details with the official source.</p></div></div><div className="actions"><button className="btn ghost" onClick={()=>go("need")}><ArrowLeft/> Back</button><button className="btn primary" onClick={()=>go("documents")}>Check my documents <ArrowRight/></button></div></PageShell>}
function DocumentsPage({docs,setDocs,go,setExplain,addReminder}){const ready=docs.filter(d=>d.status==="available").length;return <PageShell eyebrow="STEP 3 · DOCUMENTS" title="Know what you need before you start" subtitle="Check each requirement and resolve missing documents before filling the form." onBack={()=>go("service")}><div className="readiness"><div><span className="muted">APPLICATION READINESS</span><h2>{Math.round(ready/docs.length*100)}%</h2><p>{ready} of {docs.length} documents ready</p></div><div className="readiness-bar"><span style={{width:`${ready/docs.length*100}%`}}/></div></div><div className="doc-list">{docs.map(d=><div className={`doc-item status-${d.status}`} key={d.key}><StatusIcon status={d.status}/><div className="grow"><div className="doc-title"><b>{d.name}</b><span className="status-pill">{statusLabel(d.status)}</span></div><p>{d.text}</p>{d.status==="missing"&&<div className="missing-actions"><button onClick={()=>addReminder()}><Clock3 size={14}/> Remind me</button><button onClick={()=>setExplain({title:`How to get ${d.name}`,text:`FormEase can explain the usual process, but the exact authority and requirements depend on your location. Open the official service portal and verify the current steps before applying.`})}>How to get it</button></div>}</div><div className="doc-actions"><button className="text-btn" onClick={()=>setExplain({title:d.name,text:d.text+" Only provide a document if it is genuinely required for your application."})}><CircleHelp size={16}/> Why?</button><select value={d.status} onChange={e=>setDocs(p=>p.map(x=>x.key===d.key?{...x,status:e.target.value}:x))}><option value="available">Available</option><option value="not_selected">Not selected</option><option value="missing">Missing</option><option value="expired">Expired</option><option value="not_required">Not required</option></select></div></div>)}</div><div className="document-upload"><div><Upload size={21}/><div><b>Need to add a document?</b><p>Choose a PDF, image or photo in a real implementation.</p></div></div><button className="btn secondary" onClick={()=>setExplain({title:"Document upload",text:"This prototype shows the upload experience. A production version should scan files securely, extract only necessary information and clearly tell you what was detected."})}>Choose file</button></div><div className="actions"><button className="btn ghost" onClick={()=>go("service")}><ArrowLeft/> Back</button><button className="btn primary" onClick={()=>go("form")}>Continue to guided form <ArrowRight/></button></div></PageShell>}
function FormPage({form,update,age,go,setExplain,toggleVoice,voice}){return <PageShell eyebrow="STEP 4 · GUIDED FORM" title="Answer simple questions" subtitle="FormEase breaks a complicated form into small, understandable steps." onBack={()=>go("documents")}><div className="form-progress-note"><span><Sparkles size={15}/> Smart assistance enabled</span><b>Section 1 of 2</b></div><div className="form-card"><FormField label="Full name" required value={form.name} onChange={v=>update("name",v)} field="name" onExplain={setExplain} voice={voice} onVoice={toggleVoice}/><div className="two-fields"><FormField label="Date of birth" required type="date" value={form.dob} onChange={v=>update("dob",v)} field="dob" onExplain={setExplain}/><div className="calculated"><label>Age</label><div>{age}<small>years</small></div><span>Calculated automatically from DOB</span></div></div><FormField label="Mobile number" required value={form.mobile} onChange={v=>update("mobile",v)} field="mobile" onExplain={setExplain} placeholder="10-digit number" voice={voice} onVoice={toggleVoice}/><div className="two-fields"><div className="field"><div className="label-row"><label>Occupation <span className="required">*</span></label><button className="explain-btn" onClick={()=>setExplain({title:"Occupation",text:explainField("occupation")})}><CircleHelp size={15}/> Explain</button></div><select value={form.occupation} onChange={e=>update("occupation",e.target.value)}><option value="">Select occupation</option><option>Student</option><option>Employed</option><option>Self-employed</option><option>Unemployed</option><option>Other</option></select></div><div className="field"><div className="label-row"><label>Purpose</label></div><select value={form.purpose} onChange={e=>update("purpose",e.target.value)}><option>Education</option><option>Scholarship</option><option>Government scheme</option><option>Other</option></select></div></div><div className="income-row"><FormField label="Income amount" required value={form.income} onChange={v=>update("income",v)} field="income" onExplain={setExplain}/><div className="field"><label>Frequency <span className="required">*</span></label><select value={form.incomeFrequency} onChange={e=>update("incomeFrequency",e.target.value)}><option value="">Choose</option><option>Monthly</option><option>Yearly</option></select></div></div></div><div className="ai-tip"><Bot size={17}/><div><b>AI tip</b><p>Use the help button beside a field for a plain-language explanation and an example.</p></div></div><div className="actions"><button className="btn ghost" onClick={()=>go("documents")}><ArrowLeft/> Back</button><button className="btn primary" onClick={()=>go("check")}>Check my application <Sparkles/></button></div></PageShell>}
function FormField({label,required,value,onChange,type="text",placeholder,field,onExplain,voice,onVoice}){return <div className="field"><div className="label-row"><label>{label} {required&&<span className="required">*</span>}</label><div className="field-tools">{onVoice&&<button className={voice?"explain-btn active":"explain-btn"} onClick={onVoice} title="Voice input"><Mic size={14}/></button>}<button className="explain-btn" onClick={()=>onExplain({title:label,text:explainField(field)})}><CircleHelp size={15}/> Explain</button></div></div><input type={type} value={value||""} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>}
function CheckPage({checked,issues,runCheck,loading,go}){return <PageShell eyebrow="STEP 5 · AI CHECK" title="Catch mistakes before you submit" subtitle="We'll look for missing information, formatting issues and obvious contradictions." onBack={()=>go("form")}>{!checked?<div className="check-start"><div className="big-ai"><Bot size={42}/></div><h2>Ready for an AI-assisted check?</h2><p>We'll inspect the information and document statuses in this prototype and explain what needs attention.</p><button className="btn primary large" onClick={runCheck} disabled={loading}>{loading?"Checking your application...":"Run AI Form Check"}<Sparkles/></button></div>:<><div className={`check-result ${issues.length?"has-issues":"ready"}`}><div className="result-icon">{issues.length?<AlertTriangle/>:<CheckCircle2/>}</div><div><span className="muted">AI CHECK COMPLETE</span><h2>{issues.length?`${issues.length} ${issues.length===1?"issue":"issues"} found`:"Your application looks ready"}</h2><p>{issues.length?"Fix these before continuing.":"No obvious prototype issues were detected."}</p></div></div>{issues.length?<div className="issues">{issues.map((i,idx)=><div className="issue" key={i.field}><div className="issue-num">{idx+1}</div><div className="grow"><b>{i.title}</b><p>{i.message}</p><div className="fix"><Sparkles size={14}/><span><b>How to fix:</b> {i.fix}</span></div></div><button className="text-btn" onClick={()=>go("form")}><Pencil size={16}/> Fix</button></div>)}</div>:<div className="passed-list">{["Required fields checked","Mobile number format checked","Age calculated from DOB","Income frequency confirmed","Document statuses reviewed","No obvious contradictions detected"].map(x=><div key={x}><CheckCircle2 size={18}/>{x}</div>)}</div>}<div className="actions"><button className="btn ghost" onClick={()=>go("form")}><Pencil/> Edit</button>{issues.length?<button className="btn primary" onClick={()=>{go("form")}}>Fix issues <ArrowRight/></button>:<button className="btn primary" onClick={()=>go("review")}>Review application <ArrowRight/></button>}</div></>}</PageShell>}
function ReviewPage({form,docs,age,go,createApplication}){return <PageShell eyebrow="STEP 6 · FINAL REVIEW" title="Review before you continue" subtitle="Check your information one last time. Final submission happens through the official government portal." onBack={()=>go("check")}><div className="review-grid"><ReviewCard title="Personal information" onEdit={()=>go("form")} rows={[["Full name",form.name],["Date of birth",form.dob],["Age",age+" years"],["Mobile",form.mobile]]}/><ReviewCard title="Application" onEdit={()=>go("form")} rows={[["Purpose",form.purpose],["Occupation",form.occupation],["Income",`₹${form.income} / ${form.incomeFrequency||"—"}`]]}/><ReviewCard title="Documents" onEdit={()=>go("documents")} rows={docs.map(d=>[d.name,statusLabel(d.status)])}/><div className="official-card"><ExternalLink/><div><b>Official submission</b><p>When integrated, this button should open the verified official portal for the selected service.</p><button className="text-btn">Official portal guidance <ArrowRight size={14}/></button></div></div></div><div className="ready-banner"><CheckCircle2/><div><b>Ready for final review</b><p>AI assistance is guidance only and does not guarantee eligibility or approval.</p></div></div><div className="actions"><button className="btn ghost" onClick={()=>go("check")}><ArrowLeft/> Back</button><button className="btn primary large" onClick={createApplication}>Save & continue to official portal <ExternalLink/></button></div></PageShell>}
function ReviewCard({title,rows,onEdit}){return <div className="review-card"><div className="review-head"><h3>{title}</h3><button className="text-btn" onClick={onEdit}><Pencil size={14}/> Edit</button></div>{rows.map(([a,b])=><div className="review-row" key={a}><span>{a}</span><b>{b||"—"}</b></div>)}</div>}
function SubmittedPage({applications,go,addReminder}){const app=applications[0];return <div className="submitted page"><div className="success-orb"><CheckCircle2 size={52}/></div><span className="eyebrow">APPLICATION SAVED</span><h1>Your application is ready for the next step</h1><p className="lead">The prototype saved your application. No information was sent to a government system.</p><div className="app-id"><span>Reference</span><b>{app?.id||"FE-2026-DEMO"}</b></div><div className="timeline">{[["Application prepared",true],["Information reviewed",true],["Documents checked",true],["Official submission",false],["Government processing",false]].map(([x,on],i)=><div className={`timeline-row ${on?"done":""}`} key={x}><div className="timeline-dot">{on?<Check size={13}/>:i+1}</div><div><b>{x}</b><p>{on?"Completed in FormEase prototype":"Next step depends on the official portal."}</p></div></div>)}</div><div className="notice"><ShieldCheck size={18}/><div><b>Important</b><p>Open the verified official government portal to actually submit. FormEase AI does not issue certificates or make government decisions.</p></div></div><div className="actions center-actions"><button className="btn secondary" onClick={addReminder}><Bell/> Add status reminder</button><button className="btn primary" onClick={()=>go("dashboard")}>View My Applications <ArrowRight/></button></div></div>}
function Dashboard({apps,reminders,go,addReminder}){return <PageShell eyebrow="MY SPACE" title="Your application dashboard" subtitle="Everything that needs your attention, in one place." onBack={()=>go("home")}><div className="welcome-banner"><div><span className="muted">WELCOME BACK 👋</span><h2>Let's keep things moving.</h2><p>You have {apps.length} saved application{apps.length!==1?"s":""} and {reminders.filter(r=>!r.done).length} active reminder{reminders.filter(r=>!r.done).length!==1?"s":""}.</p></div><button className="btn primary" onClick={()=>go("need")}>Start something new <Plus/></button></div><div className="dashboard-grid"><div className="dash-main"><div className="section-row"><div><span className="eyebrow">ACTIVE</span><h2>My applications</h2></div><button className="btn text-only" onClick={()=>go("services")}>Find service <ArrowRight/></button></div>{apps.length?apps.map(a=><ApplicationCard key={a.id} app={a} onClick={()=>go("submitted")}/>):<EmptyState icon={<FolderOpen/>} title="No applications yet" text="Start by telling FormEase what you need." action="Find a service" onClick={()=>go("services")}/>}</div><div className="side-stack"><MiniPanel title="Action required"><div className="action-item"><AlertTriangle/><span><b>Check your documents</b><small>Resolve missing or expired items before continuing.</small></span><ChevronRight/></div></MiniPanel><MiniPanel title="Upcoming"><div className="action-item"><CalendarClock/><span><b>Application status</b><small>Check again in 3 days.</small></span><button className="text-btn" onClick={addReminder}>Remind</button></div></MiniPanel><MiniPanel title="Explore"><div className="explore-links"><button onClick={()=>go("schemes")}><Sparkles/> Scheme Finder</button><button onClick={()=>go("documents")}><FileCheck2/> Document readiness</button><button onClick={()=>go("need")}><MessageCircle/> Ask FormEase AI</button></div></MiniPanel></div></div></PageShell>}
function ApplicationCard({app,onClick}){return <button className="application-card" onClick={onClick}><div className="application-top"><div className="service-icon"><FileText/></div><span className="status-pill warning">{app.status}</span></div><h3>{app.service}</h3><p>Reference: <b>{app.id}</b></p><div className="app-progress"><span style={{width:`${app.progress}%`}}/></div><div className="application-bottom"><span>{app.progress}% complete</span><span>Last saved {app.date}</span><ChevronRight/></div></button>}
function MiniPanel({title,children}){return <div className="mini-panel"><div className="mini-panel-head"><b>{title}</b></div>{children}</div>}
function Reminders({reminders,setReminders,go}){return <PageShell eyebrow="REMINDERS" title="Never miss the next step" subtitle="Keep deadlines, follow-ups and renewals in one simple list." onBack={()=>go("home")}><div className="reminder-add"><div><Bell/><div><b>Need a reminder?</b><p>Add one for an application, document or deadline.</p></div></div><button className="btn primary" onClick={()=>setReminders(p=>[{id:Date.now(),title:"Follow up on my application",date:new Date(Date.now()+86400000*7).toISOString().slice(0,10),done:false},...p])}><Plus/> Add reminder</button></div><div className="reminder-list">{reminders.length?reminders.map(r=><div className={`reminder ${r.done?"done":""}`} key={r.id}><button className="round-check" onClick={()=>setReminders(p=>p.map(x=>x.id===r.id?{...x,done:!x.done}:x))}>{r.done&&<Check size={14}/>}</button><div className="grow"><b>{r.title}</b><span><CalendarClock size={14}/> {r.date}</span></div><button className="icon-btn" onClick={()=>setReminders(p=>p.filter(x=>x.id!==r.id))}><X size={16}/></button></div>):<EmptyState icon={<Bell/>} title="You're all caught up" text="Add reminders when you need a nudge."/>}</div></PageShell>}
function Notifications({reminders,go}){return <PageShell eyebrow="NOTIFICATIONS" title="Updates that matter" subtitle="Important actions and reminders appear here." onBack={()=>go("home")}><div className="notification-list">{reminders.filter(r=>!r.done).map(r=><div className="notification"><div className="notification-icon"><Bell size={17}/></div><div><b>{r.title}</b><p>Reminder scheduled for {r.date}.</p></div><span className="muted">Action</span></div>)}{!reminders.filter(r=>!r.done).length&&<EmptyState icon={<CheckCircle2/>} title="No new notifications" text="You're all caught up."/>}</div></PageShell>}
function Profile({language,setLanguage,simpleMode,setSimpleMode,go}){return <PageShell eyebrow="PROFILE & SETTINGS" title="Make FormEase work for you" subtitle="Choose your language and accessibility preferences." onBack={()=>go("home")}><div className="settings-card"><div className="setting-row"><div className="setting-icon"><Languages/></div><div className="grow"><b>Preferred language</b><p>AI guidance and interface language.</p></div><select value={language} onChange={e=>setLanguage(e.target.value)}>{LANGUAGES.map(l=><option key={l}>{l}</option>)}</select></div><div className="setting-row"><div className="setting-icon"><SlidersHorizontal/></div><div className="grow"><b>Simple Mode</b><p>Use shorter explanations and more visual guidance.</p></div><button className={`toggle ${simpleMode?"on":""}`} onClick={()=>setSimpleMode(!simpleMode)}><span/></button></div><div className="setting-row"><div className="setting-icon"><ShieldCheck/></div><div className="grow"><b>Privacy-first prototype</b><p>Demo data is stored locally in this browser. Do not enter real sensitive documents into the prototype.</p></div></div></div><div className="notice"><ShieldCheck size={18}/><div><b>Independent service</b><p>FormEase AI is not a government department. Always verify requirements on the official source.</p></div></div></PageShell>}
function Schemes({query,setQuery,go}){const schemes=["Post-Matric Scholarship","Student financial assistance","Women entrepreneurship support","Senior citizen welfare","Small business support"];const list=schemes.filter(x=>x.toLowerCase().includes(query.toLowerCase()));return <PageShell eyebrow="AI SCHEME FINDER" title="Find schemes that may fit your needs" subtitle="Tell FormEase what you're looking for and we'll help you explore relevant categories." onBack={()=>go("home")}><div className="search-box"><Sparkles/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="e.g. scholarship for college, student support..."/></div><div className="scheme-grid">{list.map((x,i)=><div className="scheme-card" key={x}><div className="scheme-icon"><Sparkles/></div><div><span className="eyebrow">POTENTIAL MATCH</span><h3>{x}</h3><p>Explore eligibility, documents, benefits and the official application source.</p><button className="text-btn" onClick={()=>go("need")}>Ask FormEase AI <ArrowRight size={14}/></button></div></div>)}</div><div className="notice"><ShieldCheck size={18}/><div><b>Verify before applying</b><p>Scheme rules, eligibility and deadlines can change. Use official government information for final confirmation.</p></div></div></PageShell>}
function PageShell({eyebrow,title,subtitle,children,onBack}){return <section className="page"><div className="page-heading">{onBack&&<button className="back-link" onClick={onBack}><ArrowLeft size={15}/> Back</button>}<span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p className="lead">{subtitle}</p></div>{children}</section>}
function InfoCard({icon,title,text}){return <div className="info-card"><div className="info-icon">{icon}</div><div><h3>{title}</h3><p>{text}</p></div></div>}
function StatusIcon({status}){return <div className={`status-icon ${status}`}>{status==="available"?<Check/>:status==="missing"?<AlertTriangle/>:<FileText/>}</div>}
function statusLabel(s){return ({available:"Available",not_selected:"Not selected",missing:"Missing",expired:"Expired",not_required:"Not required"}[s]||"Unknown")}
function EmptyState({icon,title,text,action,onClick}){return <div className="empty-state">{icon}<h3>{title}</h3><p>{text}</p>{action&&<button className="btn secondary" onClick={onClick}>{action}<ArrowRight/></button>}</div>}
function calculateAge(dob){if(!dob)return 0;const b=new Date(dob+"T00:00:00");const n=new Date();let a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()===b.getMonth()&&n.getDate()<b.getDate()))a--;return Math.max(0,a)}
function load(k,fallback){try{const x=localStorage.getItem(k);return x?JSON.parse(x):fallback}catch{return fallback}}
function speakText(t){if("speechSynthesis" in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}}
export default App;
